# All builds are published as artifacts so they can be downloaded and used.

image: registry.gitlab.com/satoshilabs/trezor/trezor-firmware/trezor-firmware-env.nix

# Caching
.gitlab_caching: &gitlab_caching
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .venv/

variables:
  SDL_VIDEODRIVER: "dummy"
  XDG_RUNTIME_DIR: "/var/tmp"

# Core

# Build of Core into firmware. Regular version.
# **Are you looking for Trezor T firmware build? This is most likely it.**
core fw regular build:
  stage: build
  <<: *gitlab_caching
  needs: []
  script:
    - nix-shell --run "ulimit -S -u"
    - nix-shell --run "ulimit -H -u"
    - nix-shell --run "ulimit -a"
    - nix-shell --run "for F in /proc/sys/kernel/*threads*; do echo $F; cat $F; done"
  tags:
    - runner0_dind
